---
# Items that apply to ALL profiles and lookup prop by all clients to register with eureka server:
# act as central repository for managing the configuration properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/          # eureka server URL

---
spring:
  profiles: subject
words: Config_I,Config_You,Config_He,Config_She,Config_It
  
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: config_A,config_The

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
  
